### ISSUE TITLE
Where does log file reside?

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/NetFixServer#19]
I was planning on encapsulating the log file access by removing the following line:

```C++
extern std::ostream &logFile;
```
However, I do not actually understand where the log file goes. Below is the initialization. I think the reference (&) should be removed. I don't understand what setting it equivalent to std::cerr does though and didn't want to manipulate it without understanding the purpose.

```C++
std::ostream &logFile = std::cerr;
```

**Comment by DanRStevens** [comment]
By default, logging is done to `std::cerr`. However, the code always references `logFile` rather than `std::cerr` directly, so it can be redirected somewhere else quite easily. Perhaps it could log to a file instead. By using a base class reference, a new destination can be set with a one line change, rather than replacing all logging references.

I don't really use that older syntax style anymore, where the `&` (or `*`) is placed next to the variable name rather than the type. It was promoted back in the back because it matched C++ parsing rules, and mattered if you were declaring multiple variables on one line. It's become bad practice to declare multiple variables on one line though. These days I would prefer:
```cpp
std::ostream& logFile = std::cerr;
```

**Comment by Brett208** [comment]
I prefer the 'newer' syntax as well although it doesn't really bother me either way.

I was more speaking that I had never seen an `ostream` set to `std::cerr`. Although now that you explain it, it makes sense. Thanks.
