### ISSUE TITLE
Resolve unaligned pointer value warning (Macintosh build)

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/NetFixServer#36]
The TravisCI Macintosh gcc and clang builds both report the warning below:

```
Packet.cpp:13:16: warning: taking address of packed member 'checksum' of class or structure 'PacketHeader' may result in an unaligned pointer value [-Waddress-of-packed-member]
        int* data = (&header.checksum) + 1;
                      ^~~~~~~~~~~~~~~
```

I'm not actually sure how to resolve this warning.

**Comment by DanRStevens** [comment]
I'm not too sure either. We do need to process potentially unaligned data here.

The math does look a bit confusing, so I would like to change it. It's using pointer addition where `sizeof` the type is 4, so that `+ 1` is actually `+ 1 * 4` in terms of the memory byte address.

Maybe the `TransportLayerMessage` `union` can have a `char[]` field added to it. We could potentially take the address of that to get the data after the `checksum` field. By using a `char*` pointer type, that should avoid the warning. Though we would need to cast it to an `int*` to use it in the code as written.

Considering how the checksum code works though, a `static_cast` would be quite appropriate.

**Comment by DanRStevens** [comment]
The following seems to eliminate the warning for Clang:
```cpp
auto* data = reinterpret_cast<char*>(&header.checksum) + 4;
```

A `char` datatype is generally byte size, and so can't really be unaligned.

Of course, that changes the underlying datatype and some of the later code tries to process in 4 byte chunks. Perhaps more accurately, it should be:
```cpp
auto* data = reinterpret_cast<int*>(reinterpret_cast<char*>(&header.checksum) + 4);
```

----

I don't know if the above is the best solution. It still has the magic offset of `+ 4`. Updating the `TransportLayerMessage` `union` may provide a better alternative without the use of a magic number.

----

Note sure if I should use `char*`, `unsigned char*`, or `uint8_t*` as the intermediary type.

**Comment by Brett208** [comment]
Ok, do we want to hold off on solving until post new repository with a new union then? I'm fine with either waiting or just using the reinterpret_cast solution to silence the warning for now.

**Comment by DanRStevens** [comment]
I think I'll go with the `reinterpret_cast` solution for now.

We can defer to a later PR on the `union` part to eliminate the magic number offset. It probably makes more sense to do that change post repository merge, since `Packet` layout and checksums are kind of a shared thing.

The `union` change would eliminate the inner `reinterpret_cast`, while leaving the outer one as is.
